- hosts: nodes
  roles:
  - base

- hosts: freegeoip
  roles:
  - nodeexporter
  - freegeoip
  - redis
  vars:
    nodeexporter_url: http://github.com/prometheus/node_exporter/releases/download/0.11.0/node_exporter-0.11.0.linux-amd64.tar.gz
    freegeoip_url: https://github.com/fiorix/freegeoip/releases/download/v3.0.10/freegeoip-3.0.10-linux-amd64.tar.gz
    freegeoip_params:
    - -http=:80
    - -https=:443
    - -cert=/etc/ssl/certs/freegeoip.pem
    - -key=/etc/ssl/private/freegeoip.key
    - -internal-server=:8888
    - -silent
    - -public=/opt/freegeoip/public
    - -quota-max=10000
    - -quota-interval=1h
    - -redis={% for host in groups['freegeoip'] %}{{ hostvars[host]['private_ip'] }}:6379{% if not loop.last %},{% endif %}{% endfor %}
    - -redis-timeout=1s

- hosts: monitor
  roles:
  - prometheus
  vars:
    prometheus_user: admin
    prometheus_passwd: lerolero
    prometheus_url: https://github.com/prometheus/prometheus/releases/download/0.16.1/prometheus-0.16.1.linux-amd64.tar.gz
    prometheus_params:
    - -web.listen-address=:9090
