#!/bin/bash
#
# Copyright 2010 Alexandre Fiori
# freegeoip.net
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# set to 0 for production
# 1 means run in foreground
DEBUG=1

# path to the local version of the db
DATABASE=./database/ipdb.sqlite

# port and interface to listen on
PORT=8888
LISTEN=127.0.0.1

# uncommend the following line if you're running
# the service behind nginx
#XHEADERS=-x

# set your reactor and path to log files
REACTOR=select # epoll, kqueue
LOGFILE=/var/log/freegeoip.log
PIDFILE=/var/run/freegeoip.pid

if [ $DEBUG -eq 1 ]
then
    exec twistd -n freegeoip --database=$DATABASE --port=$PORT --listen=$LISTEN
else
    exec twistd --logfile=$LOGFILE --pidfile=$PIDFILE --reactor=$REACTOR \
    freegeoip --database=$DATABASE --port=$PORT --listen=$LISTEN $XHEADERS
fi
