#!/usr/bin/env python
# coding: utf-8
#
# Copyright 2013 Alexandre Fiori
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import os
import sqlite3
import sys

dbname = "ipdb-submit.sqlite"


if __name__ == "__main__":

    # Create the IP database
    tmpdb = "_" + dbname + ".temp"
    if os.path.exists(tmpdb):
        os.unlink(tmpdb)

    conn = sqlite3.connect(tmpdb)
    curs = conn.cursor()

    curs.execute("""\
	create table client_location (
		ip int,
        latitude real,
        longitude real,
		timestamp DATE DEFAULT (datetime('now','localtime')),
        primary key(ip))""")

    curs.close()
    conn.commit()

    # Replace any existing db with the new one
    if os.path.exists(dbname):
        os.unlink(dbname)
    os.rename(tmpdb, dbname)
